---
title: "Model comparison"
author: "Francisco Rodríguez-Sánchez"
institute: "https://frodriguezsanchez.net"
aspectratio: 43  # use 169 for wide format
fontsize: 10pt
output: 
  binb::metropolis:
    keep_tex: no
    incremental: yes
    fig_caption: no
    pandoc_args: ["--lua-filter=hideslide.lua"]
urlcolor: blue
linkcolor: blue
header-includes:
  - \definecolor{shadecolor}{RGB}{230,230,230}
  # - \setbeamercolor{frametitle}{bg=black}
---


```{r knitr_setup, include=FALSE, cache=FALSE}

library("knitr")

### Chunk options ###

## Text results
opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, size = 'tiny')

## Code decoration
opts_chunk$set(tidy = FALSE, comment = NA, highlight = TRUE, prompt = FALSE, crop = TRUE)

# ## Cache
# opts_chunk$set(cache = TRUE, cache.path = "knitr_output/cache/")

# ## Plots
# opts_chunk$set(fig.path = "knitr_output/figures/")
opts_chunk$set(fig.align = 'center', out.width = '90%')

### Hooks ###
## Crop plot margins
knit_hooks$set(crop = hook_pdfcrop)

## Reduce font size
## use tinycode = TRUE as chunk option to reduce code font size
# see http://stackoverflow.com/a/39961605
knit_hooks$set(tinycode = function(before, options, envir) {
  if (before) return(paste0("\n \\", options$size, "\n\n"))
  else return("\n\n \\normalsize \n")
  })

```


## Trees dataset

```{r}
trees <- read.csv("data/trees.csv")
head(trees)
```

```{r echo=FALSE}
trees$site <- as.factor(trees$site)
```

## Four models

```{r}
m1 <- lm(height ~ dbh, data = trees)
```

```{r}
m2 <- lm(height ~ sex, data = trees)
```

```{r}
m3 <- lm(height ~ site, data = trees)
```

```{r}
m4 <- lm(height ~ site*dbh, data = trees)
```


## Compare model performance

\footnotesize

```{r}
library("performance")
compare_performance(m1, m2, m3, m4)
```


## Compare model performance

```{r out.width="70%"}
library("see")
plot(compare_performance(m1, m2, m3, m4))
```


## Compare parameters

\tiny

```{r}
library("parameters")
compare_parameters(m1, m2, m3, m4)
```


## Compare parameters

```{r}
library("parameters")
plot(compare_parameters(m1, m2, m3, m4))
```


